name: build

on: push

jobs:
  build:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
    - uses: actions-rs/cargo@v1
      with:
        command: build
      args: --release

# vim: set ts=2 sts=2 sw=2:
