name: build

on: push

jobs:
  build:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabihf
    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      run: |
        case "${{ matrix.target }}" in
          arm-* )
            git clone --depth 1 'https://github.com/raspberrypi/tools.git' ~/tools
            cat << EOF > ~/.cargo/config
        [target.${{ matrix.target }}]
        linker = "${{ env.HOME }}/tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
        EOF
            ;;
          armv7-* )
            sudo apt install gcc-arm-linux-gnueabihf
            cat << EOF > ~/.cargo/config
        [target.${{ matrix.target }}]
        linker = "gcc-arm-linux-gnueabihf"
        EOF
            ;;
        esac
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
          profile: minimal
    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}
    - name: build examples
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }} --examples
    - name: dump readelf
      run: |
        find target/release/examples -type f -executable | xargs file
        find target/release/examples -type f -executable | xargs -n1 readelf --arch-specific

# vim: set ts=2 sts=2 sw=2:
